executable = /home/barmstrong/cluster/htcondor/cuda_wrapper.sh
error = /fast/barmstrong/outputs/$(Cluster).err
output = /fast/barmstrong/outputs/$(Cluster).out
log = /fast/barmstrong/outputs/$(Cluster).log
request_memory = 48GB
request_cpus = 8
request_gpus = 1
requirements = (TARGET.CUDAGlobalMemoryMb > 10000)
MaxTime = 200000
periodic_remove = (JobStatus =?= 2) && ((CurrentTime - JobCurrentStartDate) >= $(MaxTime))
environment = "CONDOR_JOB_ID=$(Cluster).$(Process) HDF5_USE_FILE_LOCKING='FALSE'"

queue
