import logging
from pathlib import Path
from typing import Callable, List, Optional

import h5py
import jsonargparse
import matplotlib.pyplot as plt
import numpy as np

from ledger.events import EventSet, RecoveredInjectionSet
from ledger.injections import InjectionParameterSet
from plots.legacy import compute
from plots.legacy.gwtc3 import main as gwtc3_pipeline_sv
from plots.legacy.tools import SECONDS_PER_YEAR
from plots.vetos import VETO_CATEGORIES, VetoParser, get_catalog_vetos
from priors.priors import log_normal_masses
from utils.cosmology import DEFAULT_COSMOLOGY, get_astrophysical_volume
from utils.logging import configure_logging

logging.getLogger("urllib3").setLevel(logging.WARNING)

PALETTE = [
    "#1f77b4",
    "#ff7f0e",
    "#2ca02c",
    "#d62728",
    "#9467bd",
    "#8c564b",
    "#e377c2",
]

INJECTION_FILE = Path(__file__).resolve().parent.parent / (
    "legacy/endo3_mixture-LIGO-T2100113-v12-1256655642-12905976.hdf5"
)
VETO_DEFINER_FILE = (
    Path(__file__).resolve().parent.parent / "vetos/H1L1-HOFT_C01_O3_CBC.xml"
)
GATE_PATHS = {
    "H1": Path(__file__).resolve().parent.parent
    / "vetos/H1-O3_GATES_1238166018-31197600.txt",
    "L1": Path(__file__).resolve().parent.parent
    / "vetos/L1-O3_GATES_1238166018-31197600.txt",
}


def get_prob(prior, ledger):
    sample = {"mass_1": ledger.mass_1, "mass_2": ledger.mass_2}
    return prior.prob(sample, axis=0)


def plot_err_bands(ax, x, y, err, color, alpha=0.4, **kwargs):
    ax.fill_between(x, y - err, y + err, color=color, alpha=alpha, **kwargs)


def make_grid(combos):
    num_plots = len(combos)
    if num_plots not in [1, 4]:
        raise ValueError(
            f"Only support 2x2 or 1x1 grids, can't plot {num_plots} combos"
        )

    if num_plots == 1:
        fig, ax = plt.subplots(1, 1, figsize=(6, 4))
        m1, m2 = combos[0]
        ax.set_title(f"Log Normal $m_1={m1}$, $m_2={m2}$")
        ax.set_xscale("log")
        ax.set_xlabel("False Alarm Rate [yr$^{-1}$]")
        ax.set_ylabel("Sensitive Volume [Gpc$^3$]")
        return fig, [ax]

    fig, axes = plt.subplots(2, 2, figsize=(10, 7))
    axes = axes.flatten()

    for i, (ax, combo) in enumerate(zip(axes, combos, strict=True)):
        m1, m2 = combo
        ax.set_title(f"Log Normal $m_1={m1}$, $m_2={m2}$")
        ax.set_xscale("log")

        # y-axis label on left column
        if i % 2 == 0:
            ax.set_ylabel("Sensitive Volume [Gpc$^3$]")

        # x-axis label on bottom row
        if i >= 2:
            ax.set_xlabel("False Alarm Rate [yr$^{-1}$]")
        else:
            ax.set_xticklabels([])

    return fig, axes


def main(
    background: Path,
    foreground: Path,
    rejected_params: Path,
    ifos: List[str],
    mass_combos: List[tuple[float, float]],
    source_prior: Callable,
    output_dir: Path,
    log_file: Optional[Path] = None,
    dt: Optional[float] = None,
    min_fpr: float = 1,
    max_far: float = 1000,
    sigma: float = 0.1,
    verbose: bool = False,
    vetos: Optional[List[VETO_CATEGORIES]] = None,
):
    """
    Compute and plot the sensitive volume of an aframe analysis

    Args:
        background:
            Path to the background event set. Should be an HDF5 file
            readable by `ledger.events.EventSet.read`
        foreground:
            Path to the foreground event set. Should be an HDF5 file
            readable by `ledger.injections.RecoveredInjectionSet.read`
        rejected_params:
            Path to the rejected parameter set. Should be an HDF5 file
            readable by `ledger.injections.InjectionParameterSet.read`
        output_dir:
            Path to the directory to save the output plots and data
        log_file:
            Path to the log file. If not provided, will log to stdout
        dt:
            If provided, enforce a recovery time delta of `dt` seconds
            between injected and recovered events. Note that your `dt`
            should be greater than 1 / `inference_sampling_rate`.
        min_fpr:
            The minimum FAR to include in plots and output data, in
            units of years^-1
        max_far:
            The maximum FAR to compute the sensitive volume out to in
            units of years^-1
        sigma:
            The width of the log normal mass distribution to use
        verbose:
            If true, log at the debug level
    """
    configure_logging(log_file, verbose)
    logging.info("Reading in inference outputs")
    background_events = EventSet.read(background)
    foreground_events = RecoveredInjectionSet.read(foreground)
    # Filter unphysical waveforms generated by IMRPhenomXPHM glitch
    # https://git.ligo.org/reed.essick/rpo4-injection-triage/-/blob/main/rpo4a/README.md?ref_type=heads # noqa
    mask = foreground_events.snr > 1e4
    num_unphysical = sum(mask)
    if num_unphysical > 0:
        foreground_events = foreground_events[~mask]
        logging.info(
            f"Removed {num_unphysical} foreground events with SNR > 10,000"
        )
    rejected_params_set = InjectionParameterSet.read(rejected_params)

    for i in range(2):
        mass = f"mass_{i + 1}"
        for ledger in [foreground_events, rejected_params_set]:
            val = getattr(ledger, mass)
            setattr(ledger, mass, val / (1 + ledger.redshift))
    logging.info("Read in:")
    logging.info(f"\t{len(background_events)} background events")
    logging.info(f"\t{len(foreground_events)} foreground_events events")
    logging.info(f"\t{len(rejected_params_set)} rejected events")

    start, stop = (
        background_events.detection_time.min(),
        background_events.detection_time.max(),
    )
    logging.info(f"Loading in vetoes from {start} to {stop}")

    # optionally apply vetos
    if vetos is not None:
        veto_parser = VetoParser(
            VETO_DEFINER_FILE,
            GATE_PATHS,
            start,
            stop,
            ifos,
        )

        catalog_vetos = get_catalog_vetos(start, stop)

        for cat in vetos:
            for i, ifo in enumerate(ifos):
                if cat == "CATALOG":
                    vetos = catalog_vetos
                else:
                    vetos = veto_parser.get_vetos(cat)[ifo]
                back_count = len(background_events)
                fore_count = len(foreground_events)
                if len(vetos) > 0:
                    background_events = background_events.apply_vetos(vetos, i)
                    foreground_events = foreground_events.apply_vetos(vetos, i)
                logging.info(
                    f"\t{back_count - len(background_events)} {cat} "
                    f"background events removed for ifo {ifo}"
                )
                logging.info(
                    f"\t{fore_count - len(foreground_events)} {cat} "
                    f"foreground events removed for ifo {ifo}"
                )

    logging.info("Computing data likelihood under source prior")
    source, _ = source_prior(DEFAULT_COSMOLOGY)
    source_probs = get_prob(source, foreground)
    source_rejected_probs = get_prob(source, rejected_params_set)

    logging.info("Computing maximum astrophysical volume")
    zprior = source["redshift"]
    zmin, zmax = zprior.minimum, zprior.maximum

    try:
        decprior = source["dec"]
    except KeyError:
        decrange = None
    else:
        decrange = (decprior.minimum, decprior.maximum)
    v0 = get_astrophysical_volume(zmin, zmax, DEFAULT_COSMOLOGY, decrange)
    v0 /= 10**9

    Tb = background_events.Tb / SECONDS_PER_YEAR
    max_events = int(max_far * Tb)
    all_fars = np.arange(1, max_events + 1) / Tb
    thresholds = np.sort(background_events.detection_statistic)[-max_events:][
        ::-1
    ]

    weights = np.zeros((len(mass_combos), len(source_probs)))
    for i, combo in enumerate(mass_combos):
        logging.info(f"Computing likelihoods under {combo} log normal")
        prior, _ = log_normal_masses(
            *combo, sigma=sigma, cosmology=DEFAULT_COSMOLOGY
        )
        prob = get_prob(prior, foreground_events)
        rejected_prob = get_prob(prior, rejected_params_set)

        weight = prob / source_probs

        rejected_weights = rejected_prob / source_rejected_probs
        norm = weight.sum() + rejected_weights.sum()
        weight /= norm

        if dt is not None:
            logging.info(f"Enforcing recovery time delta of {dt} seconds")
            mask = (
                np.abs(
                    foreground_events.detection_time
                    - foreground_events.injection_time
                )
                <= dt
            )
            weight[~mask] = 0

        weights[i] = weight

    logging.info("Computing sensitive volume at thresholds")
    aframe_sv, aframe_err = compute.sensitive_volume(
        foreground_events.detection_statistic, weights, thresholds
    )
    aframe_sv *= v0
    aframe_err *= v0

    fpr_mask = all_fars >= min_fpr
    fars = all_fars[fpr_mask]
    thresholds = thresholds[fpr_mask]
    aframe_sv = aframe_sv[:, fpr_mask]
    aframe_err = aframe_err[:, fpr_mask]

    output_dir.mkdir(exist_ok=True, parents=True)
    with h5py.File(output_dir / "sensitive_volume.h5", "w") as f:
        f.create_dataset("thresholds", data=thresholds)
        f.create_dataset("fars", data=fars)
        for i, combo in enumerate(mass_combos):
            g = f.create_group("-".join(map(str, combo)))
            g.create_dataset("sv", data=aframe_sv[i])
            g.create_dataset("err", data=aframe_err[i])

    logging.info("Calculating SV vs FAR for GWTC-3 pipelines")
    gwtc3_sv, gwtc3_err = gwtc3_pipeline_sv(
        mass_combos=mass_combos,
        injection_file=INJECTION_FILE,
        detection_criterion="far",
        detection_thresholds=fars,
        output_dir=output_dir,
    )

    fig, axes = make_grid(mass_combos)

    for ax in axes:
        ax.set_xlim(min_fpr, max_far)

    for i, ax in enumerate(axes):
        color = PALETTE[0]
        label = "aframe" if i == 0 else None
        ax.plot(
            fars,
            aframe_sv[i],
            linewidth=1.5,
            color=color,
            label=label,
            alpha=0.5 if i != 0 else 1,
            zorder=5 if i == 0 else 1,
        )  # make aframe lines transparent in all but first plot
        plot_err_bands(ax, fars, aframe_sv[i], aframe_err[i], color=color)

        for pipeline, color in zip(gwtc3_sv.keys(), PALETTE[1:], strict=True):
            m1, m2 = mass_combos[i]
            mass_key = f"{m1}-{m2}"
            sv = gwtc3_sv[pipeline][mass_key]
            err = gwtc3_err[pipeline][mass_key]

            label = pipeline if i == 0 else None
            ax.plot(fars, sv, linewidth=1.5, color=color, label=label)
            plot_err_bands(ax, fars, sv, err, color=color)

    # Add legend to first axis
    handles, labels = axes[0].get_legend_handles_labels()
    axes[0].legend(
        handles,
        labels,
        loc="upper left",
        fontsize=8,
        ncol=2,
        handlelength=1.5,
        borderpad=0.4,
        labelspacing=0.3,
    )

    fig.tight_layout()
    fig.savefig(output_dir / "sensitive_volume.png", bbox_inches="tight")
    plt.close(fig)


if __name__ == "__main__":
    parser = jsonargparse.ArgumentParser()
    parser.add_function_arguments(main)
    args = parser.parse_args()
    main(**vars(args))
