model:
  class_path: train.model.jax_supervised.JaxSupervisedAframe
  init_args:
    arch:
      class_path: architectures.supervised.SupervisedTimeDomainLinOSS
      init_args:
        time_in_features: 2
        time_hidden_dim: 16
        time_num_blocks: 4
        time_dropout_rate: 0.0
        time_state_dim: 32
        time_r_min: 0.9
        time_theta_max: 3.14159265359
        time_num_res_blocks: 2
        time_conv_kernel_size: 51
        time_conv_position: post
        resnet_layers: [2, 2, 2]
        resnet_latent_dim: 64
        resnet_kernel_size: 51
        resnet_norm_groups: 16
        mlp_width: 64
        mlp_depth: 2

    metric:
      class_path: train.metrics.TimeSlideAUROC
      init_args:
        max_fpr: 1e-3
        pool_length: 8

    learning_rate: 5e-5
    pct_lr_ramp: 0.115
    weight_decay: 3e-5
    max_steps: 500000
    warmup_steps: 4000
    clip_grad_norm: 10.0
    seed: 43

data:
  class_path: train.data.supervised.TimeDomainSupervisedAframeDataset
  init_args:
    waveforms_dir: /home/barmstrong/aframe_new/data/bns/aframe_train/
    background_dir: /home/barmstrong/aframe_new/data/bns/background_data
    ifos: [H1, L1]
    sample_rate: 2048
    batches_per_epoch: 2000
    num_files_per_batch: 10
    chunk_size: 1000
    chunks_per_epoch: 20
    batch_size: 128
    val_batch_size: 256
    kernel_length: 4
    psd_length: 20
    fduration: 2
    max_num_workers: 16
    waveform_prob: 0.277
    swap_prob: 0.014
    mute_prob: 0.055
    left_pad: 3.95
    right_pad: 0.05
    fftlength: 2
    snr_sampler:
      class_path: ml4gw.distributions.PowerLaw
      init_args:
        minimum: 8
        maximum: 100
        index: -3
    waveform_sampler:
      class_path: train.data.waveforms.WaveformLoader
      init_args:
        training_waveform_path: /home/barmstrong/aframe_new/data/bns/aframe_train/training_waveforms.hdf5
        val_waveform_file: /home/barmstrong/aframe_new/data/bns/aframe_train/val_waveforms.hdf5
    dec:
      class_path: ml4gw.distributions.Cosine
    psi:
      class_path: torch.distributions.Uniform
      init_args:
        low: 0
        high: 3.14159
        validate_args: false
    phi:
      class_path: torch.distributions.Uniform
      init_args:
        low: 0
        high: 6.28318
        validate_args: false
    valid_stride: 0.5
    num_valid_views: 5
    valid_livetime: 57600

trainer:
  logger:
    - class_path: train.callbacks.AframeWandbLogger
      init_args:
        name: "linoss_conv_post_ks51"
        save_dir: lightning_logs
        project: "aframe"
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "val/valid_auroc_epoch"
        mode: "max"
        patience: 500
    - class_path: train.utils.jax.save_model.JAXCheckpointManager
      init_args:
        monitor: "val/valid_auroc_epoch"
        mode: "max"
        save_top_k: 5
    - class_path: train.callbacks.SaveAugmentedBatch
    - class_path: train.utils.data_wait_timer.DataWaitTimer
    - class_path: train.utils.samples_per_second.SamplesPerSecondTimer
    - class_path: train.metric.plotting.FgBgScoreDistributionCallback
    - class_path: train.metric.plotting.EfficiencyVsSnrCallback
  accelerator: auto
  max_epochs: 800
  check_val_every_n_epoch: 1
  enable_progress_bar: true
  benchmark: true
