seed_everything: 20260612

trainer:
  accelerator: auto
  devices: auto
  max_epochs: 100000
  check_val_every_n_epoch: 2
  gradient_clip_val: 1.0
  log_every_n_steps: 20
  enable_progress_bar: true
  default_root_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/aframe/dev/runs/merger_4s_big_s4d_resnet/train/class/s4d_resnet_regdev

  logger:
    - class_path: train.callbacks.AframeWandbLogger
      init_args:
        name: s4d_resnet_regdev
        id:   s4d_resnet_regdev
        save_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/aframe/dev/runs/merger_4s_big_s4d_resnet/train/class/s4d_resnet_regdev
        project: BNS-PUBLICATION-CLASS

  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: validation/TimeSlideAUROC
        mode: max
        save_top_k: 3
        save_last: true
        filename: 's4d_cls_auroc_{epoch:02d}'
        auto_insert_metric_name: false
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: validation/TimeSlideAUROC
        mode: max
        patience: 100000
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch

model:
  class_path: train.model.supervised_ky.SupervisedAframeS4CustomLR
  init_args:
    arch:
      class_path: architectures.supervised.SupervisedS4ModelResNetMLPDecoder
      init_args:
        num_ifos: 2
        d_output: 1
        d_model: 256
        d_state: 32
        n_layers: 4
        dropout: 0.2
        dt_min: 1.0e-3
        dt_max: 5.0
    metric:
      class_path: train.metrics.TimeSlideAUROC
      init_args:
        max_fpr: 1e-3
        pool_length: 50
    learning_rate: 1e-4
    ssm_lr: 1e-3
    normalize_input: true
    warm_start_ckpt: null
    pct_lr_ramp: 0.0
    weight_decay: 0.01
    lr_scheduler:
      class_path: train.model.regression_ky.WarmupCosineAnnealingWarmRestarts
      init_args:
        warmup_epochs: 1
        T_0: 140
        T_mult: 2
        eta_min: 1.0e-7
    lr_scheduler_interval: epoch

data:
  class_path: train.data.supervised.TimeDomainSupervisedAframeDataset
  init_args:
    background_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/O3a_H1_L1_2048Hz
    waveforms_dir: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/aframe_data/train
    ifos: [H1, L1]
    sample_rate: 2048

    kernel_length: 4.0
    left_pad: 3.5
    right_pad: 0.0

    batch_size: 64
    batches_per_epoch: 781
    chunk_size: 2000
    chunks_per_epoch: 25
    num_files_per_batch: 1

    fduration: 1.0
    fftlength: 2.0
    psd_length: 20.0
    highpass: 20

    waveform_prob: 0.5
    swap_prob: 0.0
    mute_prob: 0.0
    max_num_workers: 8

    num_valid_views: 4
    valid_stride: 25
    valid_livetime: 210000

    snr_sampler:
      class_path: train.augmentations.SnrSampler
      init_args:
        constant_params:
          index: -2
          maximum: 100.0
        start_params:
          minimum: 4.0
        end_params:
          minimum: 4.0
        decay_steps: 100

    param_transforms:
      - class_path: train.transforms.ChirpMass

    waveform_sampler:
      class_path: train.data.waveforms.WaveformLoader
      init_args:
        ifos: [H1, L1]
        sample_rate: 2048
        num_val_waveforms: 8192
        val_waveform_file: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/aframe_data/val/end_o3_ratesandpops_bns_snr4.hdf5
        training_waveform_path: /n/holystore01/LABS/iaifi_lab/Lab/kyoon/DATA/aframe_data/train/end_o3_ratesandpops_bns_uniform_chirp.hdf5

    dec:
      class_path: ml4gw.distributions.Cosine
    psi:
      class_path: torch.distributions.Uniform
      init_args:
        low: 0.0
        high: 3.14159
        validate_args: false
    phi:
      class_path: torch.distributions.Uniform
      init_args:
        low: -3.14159
        high: 3.14159
        validate_args: false
